 steps:
   # Run test
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['test']
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'gcr.io/${PROJECT_ID}/demoimage:${COMMIT_SHA}',
           '.',
           '--build-arg', 'BRANCH_NAME=${BRANCH_NAME}',
           '--build-arg', 'NODE_ENV=${_NODE_ENV}']
  # Docker push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/demoimage:${COMMIT_SHA}']
  # Create release in Google Cloud Deploy
  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk
  #   entrypoint: gcloud
  #   args:
  #     [
  #       "deploy", "releases", "create", "rel-${SHORT_SHA}",
  #       "--delivery-pipeline", "demoapp",
  #       "--region", "asia-east1",
  #       "--annotations", "commitId=${REVISION_ID}",
  #       "--images", "demoimage=gcr.io/$PROJECT_ID/demoimage:${COMMIT_SHA}"
  #     ]
  #Deploy to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=k8s/prod.yaml
    - --image=gcr.io/${PROJECT_ID}/demoimage:${COMMIT_SHA}"
    - --location=asia-east1-b
    - --cluster=demo-cluster