apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: demoapp
description: main application pipeline
serialPipeline:
 stages:
 - targetId: demo-cluster
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: demo-cluster
description: development cluster
gke:
 cluster: projects/cogent-spring-355606/locations/asia-east1-b/clusters/demo-cluster