steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'gcr.io/${PROJECT_ID}/demoimage:latest',
           '.',
           '--build-arg', 'BRANCH_NAME=${BRANCH_NAME}']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/demoimage:latest']
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=kubernetes.yaml
    - --image=demoimage=gcr.io/${PROJECT_ID}/demoimage:latest
    - --location=asia-east1-b
    - --cluster=demo-cluster