apiVersion: v1
kind: Service
metadata:
  name: demoapp
spec:
  selector:
    app: demoapp
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-health-check
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 3
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 3000
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "demoapp"
  namespace: "default"
  labels:
    app: "demoapp"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "demoapp"
  template:
    metadata:
      labels:
        app: "demoapp"
    spec:
      containers:
      - name: "demoapp"
        image: "gcr.io/cogent-spring-355606/demoimage:latest"
        ports:
        - containerPort: 3000
  revisionHistoryLimit: 3