apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "demoapp"
  namespace: "default"
  labels:
    app: "demoapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "demoapp"
  template:
    metadata:
      labels:
        app: "demoapp"
    spec:
      containers:
      - name: "demoapp"
        image: "gcr.io/My First Project/gcr-repo:latest"
        imagePullPolicy: Always