apiVersion: skaffold/v2beta16
kind: Config
profiles:
  - name: uat
    deploy:
      kubectl:
        manifests:
        - k8s/uat.yaml
  - name: prod
    deploy:
      kubectl:
        manifests:
        - k8s/prod.yaml
