apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "demoapp"
  namespace: "default"
  labels:
    app: "demoapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "demoapp"
  template:
    metadata:
      labels:
        app: "demoapp"
    spec:
      containers:
      - name: "demoapp"
        image: "gcr.io/cogent-spring-355606/demoimage"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /prod
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3  
          successThreshold: 1
          failureThreshold: 2
  revisionHistoryLimit: 3